#!/bin/bash
../../retina contradiction.s | tee contradiction-answer.s
../../retina contradiction5.s | tee contradiction5-answer.s
../../retina contradiction-builtin.s | tee contradiction-builtin-answer.s
