#!/bin/bash
../../retina contradiction.s | tee contradiction-output-${PROLOG}.s
../../retina contradiction5.s | tee contradiction5-output-${PROLOG}.s
../../retina contradiction-builtin.s | tee contradiction-builtin-output-${PROLOG}.s
